/**
 * Git Utilities
 *
 * Helper functions for git integration.
 * Generated by Plugin Factory v1.0
 */

import { execSync } from 'child_process';

/**
 * Get the current git commit hash
 */
export function getCurrentCommit(cwd?: string): string | null {
  try {
    const commit = execSync('git rev-parse HEAD', {
      encoding: 'utf-8',
      cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    return commit;
  } catch {
    return null;
  }
}

/**
 * Get the short git commit hash
 */
export function getShortCommit(cwd?: string): string | null {
  const full = getCurrentCommit(cwd);
  return full ? full.substring(0, 7) : null;
}

/**
 * Check if a commit hash exists
 */
export function commitExists(hash: string, cwd?: string): boolean {
  try {
    execSync(`git rev-parse --verify ${hash}`, {
      encoding: 'utf-8',
      cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Get the remote URL for commit linking
 */
export function getRemoteUrl(cwd?: string): string | null {
  try {
    const remote = execSync('git remote get-url origin', {
      encoding: 'utf-8',
      cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();

    // Convert SSH to HTTPS
    if (remote.startsWith('git@')) {
      return remote
        .replace('git@', 'https://')
        .replace(':', '/')
        .replace(/\.git$/, '');
    }

    return remote.replace(/\.git$/, '');
  } catch {
    return null;
  }
}

/**
 * Build a commit URL
 */
export function buildCommitUrl(commit: string, cwd?: string): string | null {
  const remote = getRemoteUrl(cwd);
  if (!remote) return null;
  return `${remote}/commit/${commit}`;
}

/**
 * Get commit message
 */
export function getCommitMessage(hash: string, cwd?: string): string | null {
  try {
    const message = execSync(`git log -1 --format=%s ${hash}`, {
      encoding: 'utf-8',
      cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    return message;
  } catch {
    return null;
  }
}

/**
 * Check if directory is a git repository
 */
export function isGitRepo(cwd?: string): boolean {
  try {
    execSync('git rev-parse --git-dir', {
      encoding: 'utf-8',
      cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return true;
  } catch {
    return false;
  }
}
