/**
 * Add Decision Tool
 *
 * Programmatically add a new architectural decision.
 * Used by the Claude Code plugin hook and commands.
 * Generated by Plugin Factory v1.0
 */

import { z } from 'zod';
import { addDecision as addDecisionToDb } from '../db/queries.js';

export const addDecisionSchema = {
  project: z.string().describe('Project path (absolute path to project root)'),
  files: z.array(z.string()).describe('Array of file paths affected by this decision'),
  reasoning: z.string().describe('The reasoning behind the decision - the "why"'),
  commit: z.string().optional().describe('Git commit hash associated with this decision'),
  commit_url: z.string().optional().describe('URL to view the commit on GitHub/GitLab'),
  tags: z.array(z.string()).optional().describe('Tags for categorization (e.g., ["state-management", "zustand"])'),
  context: z.string().optional().describe('Additional context or notes'),
};

export type AddDecisionInput = z.infer<z.ZodObject<typeof addDecisionSchema>>;

export async function addDecision(input: AddDecisionInput) {
  const { project, files, reasoning, commit, commit_url, tags, context } = input;

  // Validate reasoning is meaningful
  if (!reasoning || reasoning.trim().length < 10) {
    return {
      content: [
        {
          type: 'text' as const,
          text: 'Decision reasoning should be at least 10 characters. Please provide meaningful context for why this decision was made.',
        },
      ],
      isError: true,
    };
  }

  try {
    const decision = addDecisionToDb({
      project,
      files,
      reasoning: reasoning.trim(),
      commit: commit || null,
      commitUrl: commit_url || null,
      tags: tags || [],
      context: context || null,
    });

    return {
      content: [
        {
          type: 'text' as const,
          text: `Decision recorded successfully.

**Decision #${decision.id}**
- Project: ${decision.project_name}
- Files: ${decision.files.join(', ')}
- Tags: ${decision.tags.length > 0 ? decision.tags.map(t => `#${t}`).join(' ') : '(none)'}
${decision.commit_hash ? `- Commit: ${decision.commit_hash}` : ''}

Query this decision anytime with: "What decisions were made about ${decision.files[0] || 'this file'}?"`,
        },
      ],
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return {
      content: [
        {
          type: 'text' as const,
          text: `Failed to record decision: ${message}`,
        },
      ],
      isError: true,
    };
  }
}
