/**
 * Export Decisions Tool
 *
 * Export decisions in various formats for documentation or sharing.
 * Generated by Plugin Factory v1.0
 */

import { z } from 'zod';
import { exportDecisions as exportDecisionsFromDb } from '../db/queries.js';

export const exportDecisionsSchema = {
  project: z.string().optional().describe('Project path to export (omit for all projects)'),
  format: z.enum(['json', 'markdown', 'adr']).default('markdown').describe('Export format: json, markdown, or adr (Architecture Decision Records)'),
};

export type ExportDecisionsInput = z.infer<z.ZodObject<typeof exportDecisionsSchema>>;

export async function exportDecisions(input: ExportDecisionsInput) {
  const { project, format } = input;

  try {
    const exported = exportDecisionsFromDb({ project, format });

    if (!exported || exported.trim() === '' || exported === '[]') {
      return {
        content: [
          {
            type: 'text' as const,
            text: `No decisions to export${project ? ` for project ${project}` : ''}.`,
          },
        ],
      };
    }

    const formatLabel = {
      json: 'JSON',
      markdown: 'Markdown',
      adr: 'Architecture Decision Records (ADR)',
    }[format];

    return {
      content: [
        {
          type: 'text' as const,
          text: `# Exported Decisions (${formatLabel})
${project ? `\nProject: ${project}` : '\nAll projects'}

---

${exported}`,
        },
      ],
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return {
      content: [
        {
          type: 'text' as const,
          text: `Export failed: ${message}`,
        },
      ],
      isError: true,
    };
  }
}
