/**
 * Get Decision Tool
 *
 * Retrieve a specific decision by ID with full details.
 * Generated by Plugin Factory v1.0
 */

import { z } from 'zod';
import { getDecision as getDecisionFromDb } from '../db/queries.js';

export const getDecisionSchema = {
  id: z.number().describe('Decision ID to retrieve'),
};

export type GetDecisionInput = z.infer<z.ZodObject<typeof getDecisionSchema>>;

export async function getDecision(input: GetDecisionInput) {
  const { id } = input;

  const decision = getDecisionFromDb(id);

  if (!decision) {
    return {
      content: [
        {
          type: 'text' as const,
          text: `Decision #${id} not found. Use query_decisions to search for available decisions.`,
        },
      ],
      isError: true,
    };
  }

  const details = [
    `# Decision #${decision.id}`,
    '',
    `**Project:** ${decision.project_name} (\`${decision.project_path}\`)`,
    `**Date:** ${new Date(decision.created_at).toLocaleString()}`,
    `**Updated:** ${new Date(decision.updated_at).toLocaleString()}`,
    '',
    '## Files Affected',
    decision.files.map(f => `- \`${f}\``).join('\n'),
    '',
    '## Reasoning',
    decision.reasoning,
    '',
  ];

  if (decision.tags.length > 0) {
    details.push('## Tags');
    details.push(decision.tags.map(t => `#${t}`).join(' '));
    details.push('');
  }

  if (decision.commit_hash) {
    details.push('## Git Reference');
    details.push(`Commit: \`${decision.commit_hash}\``);
    if (decision.commit_url) {
      details.push(`View: ${decision.commit_url}`);
    }
    details.push('');
  }

  if (decision.context) {
    details.push('## Additional Context');
    details.push(decision.context);
    details.push('');
  }

  return {
    content: [
      {
        type: 'text' as const,
        text: details.join('\n'),
      },
    ],
  };
}
