/**
 * Link Commit Tool
 *
 * Associate a decision with a specific git commit.
 * Generated by Plugin Factory v1.0
 */

import { z } from 'zod';
import { linkCommit as linkCommitInDb, getDecision } from '../db/queries.js';

export const linkCommitSchema = {
  decision_id: z.number().describe('ID of the decision to link'),
  commit_hash: z.string().describe('Git commit hash (short or full)'),
  commit_url: z.string().optional().describe('URL to view the commit (e.g., GitHub link)'),
};

export type LinkCommitInput = z.infer<z.ZodObject<typeof linkCommitSchema>>;

export async function linkCommit(input: LinkCommitInput) {
  const { decision_id, commit_hash, commit_url } = input;

  // Check if decision exists
  const decision = getDecision(decision_id);
  if (!decision) {
    return {
      content: [
        {
          type: 'text' as const,
          text: `Decision #${decision_id} not found.`,
        },
      ],
      isError: true,
    };
  }

  // Check if already linked
  if (decision.commit_hash) {
    const updateConfirm = decision.commit_hash !== commit_hash
      ? `\n\nNote: This decision was previously linked to commit ${decision.commit_hash}. The link has been updated.`
      : '';

    if (decision.commit_hash === commit_hash) {
      return {
        content: [
          {
            type: 'text' as const,
            text: `Decision #${decision_id} is already linked to commit ${commit_hash}.`,
          },
        ],
      };
    }
  }

  // Perform the link
  const success = linkCommitInDb(decision_id, commit_hash, commit_url);

  if (!success) {
    return {
      content: [
        {
          type: 'text' as const,
          text: `Failed to link decision #${decision_id} to commit ${commit_hash}.`,
        },
      ],
      isError: true,
    };
  }

  return {
    content: [
      {
        type: 'text' as const,
        text: `Successfully linked decision #${decision_id} to commit ${commit_hash}.

**Decision:** ${decision.reasoning.substring(0, 100)}...
**Commit:** ${commit_hash}${commit_url ? `\n**View:** ${commit_url}` : ''}`,
      },
    ],
  };
}
