/**
 * List Projects Tool
 *
 * List all projects that have recorded decisions.
 * Generated by Plugin Factory v1.0
 */

import { z } from 'zod';
import { listProjects as listProjectsFromDb, countProjectDecisions } from '../db/queries.js';

export const listProjectsSchema = {};

export type ListProjectsInput = z.infer<z.ZodObject<typeof listProjectsSchema>>;

export async function listProjects(_input: ListProjectsInput) {
  const projects = listProjectsFromDb();

  if (projects.length === 0) {
    return {
      content: [
        {
          type: 'text' as const,
          text: 'No projects with recorded decisions yet.\n\nUse the recall Claude Code plugin to start capturing decisions, or add decisions manually with the add_decision tool.',
        },
      ],
    };
  }

  const projectsWithCounts = projects.map(p => ({
    ...p,
    decisionCount: countProjectDecisions(p.path),
  }));

  const formatted = projectsWithCounts.map(p => {
    return `**${p.name}**
  Path: \`${p.path}\`
  Decisions: ${p.decisionCount}
  First recorded: ${new Date(p.created_at).toLocaleDateString()}`;
  }).join('\n\n');

  return {
    content: [
      {
        type: 'text' as const,
        text: `# Projects with Decision History

${formatted}

---
_${projects.length} project(s) total_

To view decisions for a project, use: \`query_decisions\` with the project path.`,
      },
    ],
  };
}
