/**
 * Recall MCP Server
 *
 * Query architectural decisions captured during Claude Code sessions.
 * Your codebase's memory - searchable forever.
 *
 * Generated by Plugin Factory v1.0
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

// Import tools
import { queryDecisions, queryDecisionsSchema } from '../src/tools/query-decisions.js';
import { addDecision, addDecisionSchema } from '../src/tools/add-decision.js';
import { getDecision, getDecisionSchema } from '../src/tools/get-decision.js';
import { linkCommit, linkCommitSchema } from '../src/tools/link-commit.js';
import { listProjects, listProjectsSchema } from '../src/tools/list-projects.js';
import { exportDecisions, exportDecisionsSchema } from '../src/tools/export-decisions.js';

// Import resources
import { getRecentResource, getProjectResource, getFileResource } from '../src/resources/decisions.js';

// Import prompts
import { generateWhyPrompt, generateDecisionSummary } from '../src/prompts/why-prompt.js';

// Initialize database (imports run schema creation)
import { DB_PATH } from '../src/db/schema.js';

const server = new McpServer({
  name: 'recall',
  version: '1.0.0',
});

// ============================================================================
// TOOLS
// ============================================================================

server.tool(
  'query_decisions',
  'Search architectural decisions by keyword or question. Use natural language like "why do we use Zustand?" or keywords like "authentication".',
  queryDecisionsSchema,
  async (args) => queryDecisions(args as Parameters<typeof queryDecisions>[0])
);

server.tool(
  'add_decision',
  'Record a new architectural decision with reasoning, affected files, and optional git commit reference.',
  addDecisionSchema,
  async (args) => addDecision(args as Parameters<typeof addDecision>[0])
);

server.tool(
  'get_decision',
  'Retrieve a specific decision by ID with full details including files, reasoning, and commit reference.',
  getDecisionSchema,
  async (args) => getDecision(args as Parameters<typeof getDecision>[0])
);

server.tool(
  'link_commit',
  'Associate an existing decision with a git commit hash for traceability.',
  linkCommitSchema,
  async (args) => linkCommit(args as Parameters<typeof linkCommit>[0])
);

server.tool(
  'list_projects',
  'List all projects that have recorded architectural decisions.',
  listProjectsSchema,
  async (args) => listProjects(args as Parameters<typeof listProjects>[0])
);

server.tool(
  'export_decisions',
  'Export decisions in JSON, Markdown, or ADR (Architecture Decision Records) format.',
  exportDecisionsSchema,
  async (args) => exportDecisions(args as Parameters<typeof exportDecisions>[0])
);

// ============================================================================
// RESOURCES
// ============================================================================

server.resource(
  'decisions://recent',
  'Recent architectural decisions across all projects',
  async () => getRecentResource()
);

// Dynamic resource templates for project and file decisions
server.resource(
  'decisions://project/*',
  'Architectural decisions for a specific project',
  async (uri) => {
    const projectPath = decodeURIComponent(uri.pathname.replace('/project/', ''));
    return getProjectResource(projectPath);
  }
);

server.resource(
  'decisions://file/*',
  'Architectural decisions related to a specific file',
  async (uri) => {
    const filePath = decodeURIComponent(uri.pathname.replace('/file/', ''));
    return getFileResource(filePath);
  }
);

// ============================================================================
// PROMPTS
// ============================================================================

server.prompt(
  'why_prompt',
  'Template for asking "why" questions about the codebase with relevant decision context',
  {
    question: z.string().describe('The question to answer, e.g., "Why do we use Zustand?"'),
    project: z.string().optional().describe('Optional project path to scope the search'),
  },
  async (args) => generateWhyPrompt(args as Parameters<typeof generateWhyPrompt>[0])
);

server.prompt(
  'decision_summary',
  'Generate an architectural decision summary for onboarding new team members',
  {
    project: z.string().describe('Project path to summarize decisions for'),
    category: z.string().optional().describe('Optional category to focus on (e.g., "authentication")'),
  },
  async (args) => generateDecisionSummary(args as Parameters<typeof generateDecisionSummary>[0])
);

// ============================================================================
// SERVER STARTUP
// ============================================================================

async function main() {
  const transport = new StdioServerTransport();

  // Handle shutdown gracefully
  process.on('SIGINT', () => {
    console.error('recall: Shutting down...');
    process.exit(0);
  });

  process.on('SIGTERM', () => {
    console.error('recall: Shutting down...');
    process.exit(0);
  });

  await server.connect(transport);
  console.error('recall MCP server running on stdio');
  console.error(`Database: ${DB_PATH}`);
}

main().catch((error) => {
  console.error('Failed to start recall server:', error);
  process.exit(1);
});
