/**
 * Decision Resources
 *
 * MCP resources for browsing decisions.
 * Generated by Plugin Factory v1.0
 */

import { getRecentDecisions, getProjectDecisions, getFileDecisions } from '../db/queries.js';

/**
 * Get recent decisions resource
 */
export function getRecentResource() {
  const decisions = getRecentDecisions(20);

  if (decisions.length === 0) {
    return {
      contents: [
        {
          uri: 'decisions://recent',
          mimeType: 'text/markdown',
          text: '# Recent Decisions\n\nNo decisions recorded yet.',
        },
      ],
    };
  }

  const content = decisions.map(d => {
    return `## #${d.id} | ${new Date(d.created_at).toLocaleDateString()}

**Project:** ${d.project_name}
**Files:** ${d.files.join(', ')}

${d.reasoning}

${d.tags.length > 0 ? `Tags: ${d.tags.map(t => `#${t}`).join(' ')}` : ''}
${d.commit_hash ? `Commit: ${d.commit_hash}` : ''}

---`;
  }).join('\n\n');

  return {
    contents: [
      {
        uri: 'decisions://recent',
        mimeType: 'text/markdown',
        text: `# Recent Decisions\n\n${content}`,
      },
    ],
  };
}

/**
 * Get project decisions resource
 */
export function getProjectResource(projectPath: string) {
  const decisions = getProjectDecisions(projectPath, 100);

  if (decisions.length === 0) {
    return {
      contents: [
        {
          uri: `decisions://project/${encodeURIComponent(projectPath)}`,
          mimeType: 'text/markdown',
          text: `# Decisions for ${projectPath}\n\nNo decisions recorded for this project.`,
        },
      ],
    };
  }

  const content = decisions.map(d => {
    return `## #${d.id} | ${new Date(d.created_at).toLocaleDateString()}

**Files:** ${d.files.join(', ')}

${d.reasoning}

${d.tags.length > 0 ? `Tags: ${d.tags.map(t => `#${t}`).join(' ')}` : ''}
${d.commit_hash ? `Commit: ${d.commit_hash}` : ''}

---`;
  }).join('\n\n');

  return {
    contents: [
      {
        uri: `decisions://project/${encodeURIComponent(projectPath)}`,
        mimeType: 'text/markdown',
        text: `# Decisions for ${decisions[0]?.project_name || projectPath}\n\n${content}`,
      },
    ],
  };
}

/**
 * Get file decisions resource
 */
export function getFileResource(filePath: string) {
  const decisions = getFileDecisions(filePath);

  if (decisions.length === 0) {
    return {
      contents: [
        {
          uri: `decisions://file/${encodeURIComponent(filePath)}`,
          mimeType: 'text/markdown',
          text: `# Decisions for ${filePath}\n\nNo decisions recorded for this file.`,
        },
      ],
    };
  }

  const content = decisions.map(d => {
    return `## #${d.id} | ${new Date(d.created_at).toLocaleDateString()}

**Project:** ${d.project_name}
**All Files:** ${d.files.join(', ')}

${d.reasoning}

${d.tags.length > 0 ? `Tags: ${d.tags.map(t => `#${t}`).join(' ')}` : ''}
${d.commit_hash ? `Commit: ${d.commit_hash}` : ''}

---`;
  }).join('\n\n');

  return {
    contents: [
      {
        uri: `decisions://file/${encodeURIComponent(filePath)}`,
        mimeType: 'text/markdown',
        text: `# Decisions for ${filePath}\n\n${content}`,
      },
    ],
  };
}
