/**
 * Why Prompt Template
 *
 * Template for asking "why" questions about the codebase.
 * Generated by Plugin Factory v1.0
 */

import { searchDecisions, getProjectDecisions } from '../db/queries.js';

export interface WhyPromptArgs {
  question: string;
  project?: string;
}

export async function generateWhyPrompt(args: WhyPromptArgs) {
  const { question, project } = args;

  // Extract key terms from the question
  const terms = question
    .toLowerCase()
    .replace(/why\s+(do|did|does|are|is|was|were)\s+(we|you|they)?\s*/gi, '')
    .replace(/[?.,!]/g, '')
    .trim();

  // Search for relevant decisions
  const decisions = searchDecisions(terms, { project, limit: 5 });

  let context = '';

  if (decisions.length > 0) {
    context = `## Relevant Decisions Found

${decisions.map(d => `### Decision #${d.id} (${new Date(d.created_at).toLocaleDateString()})
**Files:** ${d.files.join(', ')}
**Reasoning:** ${d.reasoning}
${d.tags.length > 0 ? `**Tags:** ${d.tags.map(t => `#${t}`).join(' ')}` : ''}
${d.commit_hash ? `**Commit:** ${d.commit_hash}` : ''}
`).join('\n')}

---

Based on these recorded decisions, here's the answer to "${question}":`;
  } else {
    context = `No specific decisions were recorded about this topic. Here's what I can tell you based on general context:`;
  }

  return {
    messages: [
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: `Question: ${question}

${context}`,
        },
      },
    ],
  };
}

/**
 * Decision Summary Prompt
 *
 * Generate a summary of architectural decisions for onboarding.
 */
export interface DecisionSummaryArgs {
  project: string;
  category?: string;
}

export async function generateDecisionSummary(args: DecisionSummaryArgs) {
  const { project, category } = args;

  const decisions = category
    ? searchDecisions(category, { project, limit: 50 })
    : getProjectDecisions(project, 50);

  if (decisions.length === 0) {
    return {
      messages: [
        {
          role: 'user' as const,
          content: {
            type: 'text' as const,
            text: `No architectural decisions have been recorded for this project yet. Use the recall plugin to start capturing decisions as you work.`,
          },
        },
      ],
    };
  }

  // Group decisions by tags
  const byTag: Record<string, typeof decisions> = {};
  for (const d of decisions) {
    for (const tag of d.tags) {
      if (!byTag[tag]) byTag[tag] = [];
      byTag[tag].push(d);
    }
    if (d.tags.length === 0) {
      if (!byTag['uncategorized']) byTag['uncategorized'] = [];
      byTag['uncategorized'].push(d);
    }
  }

  const summary = Object.entries(byTag)
    .sort((a, b) => b[1].length - a[1].length)
    .map(([tag, tagDecisions]) => {
      return `### ${tag} (${tagDecisions.length} decisions)
${tagDecisions.slice(0, 3).map(d => `- ${d.reasoning.substring(0, 100)}...`).join('\n')}
${tagDecisions.length > 3 ? `- ... and ${tagDecisions.length - 3} more` : ''}`;
    })
    .join('\n\n');

  return {
    messages: [
      {
        role: 'user' as const,
        content: {
          type: 'text' as const,
          text: `# Architectural Decision Summary for ${decisions[0]?.project_name || project}

This project has **${decisions.length} recorded architectural decisions**.

${summary}

---

For detailed information on any decision, ask about specific topics or use the query_decisions tool.`,
        },
      },
    ],
  };
}
